about_us/urls.py
from django.urls import path
from . import views

app_name = 'about_us'

urlpatterns = [
    path('', views.about, name='about'),
]

donasi_apd/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'apd'

urlpatterns = [
    path('', views.list_program, name='list_program'),
    path('<str:program>/', views.list_donatur, name='list_donatur_apd'),
]

donasi_sosial/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'programs'

urlpatterns = [
    path('', views.list_program, name='list_program'),
    path('<str:program>/', views.list_donatur, name='list_donatur'),
]

donavid/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import  static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')), 
    path('login/', include(('Login.urls', 'login'), namespace='login')),
    path('testimoni/', include('testimoni.urls')),
    path('donasi-sosial/', include('donasi_sosial.urls')),
    path('formulir_donasi/', include('formulir_donasi_sosial.urls')),
    path('formulir_donasi_apd/', include('formulir_donasi_apd.urls')),
    path('donasi-apd/', include('donasi_apd.urls')),
    path('about-us/', include('about_us.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

formulir_donasi_apd/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 

urlpatterns = [
    path('<str:program>', views.formulir, name='formulir_donasi_apd'),
    path('donasi_apd_berhasil/', views.berhasil, name='donasi_apd_berhasil'),
]

formulir_donasi_sosial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 

urlpatterns = [
    path('<str:program>', views.formulir, name='formulir_donasi'),
    path('donasi_berhasil/', views.berhasil, name='donasi_berhasil'),
]

homepage/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),


]

testimoni/urls.py
from django.urls import path
from . import views

app_name = 'testimoni'

urlpatterns = [
    path('', views.testimoni, name='testimoni'),
]

Login/models.py
from django.db import models

# Create your models here.

User/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

about_us/models.py
from django.db import models

# Create your models here.

donasi_apd/models.py
from django.db import models
from formulir_donasi_apd.models import DonasiAPD

# Create your models here.
class Donasiapd(models.Model):
    status = models.CharField(max_length=100)
    name   = models.CharField(max_length=200)
    photo  = models.ImageField(upload_to="static/img")
    desc   = models.TextField()
    target = models.IntegerField()
    remDay = models.IntegerField()
    donatur = models.ManyToManyField(DonasiAPD, blank=True)

homepage/models.py
from django.db import models

# Create your models here.
class Harapan(models.Model):
    nama = models.CharField(max_length=15)
    isi = models.TextField(max_length=150)

    def __str__(self):
        return self.nama

testimoni/models.py
from django.db import models

# Create your models here.
class Testimoni(models.Model):
    nama = models.CharField(max_length=15)
    isi = models.TextField(max_length=150)

    def __str__(self):
        return self.nama

User/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import UserProfile

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

homepage/forms.py
from django import forms
from django.forms import ModelForm
from django.forms import fields
from homepage.models import Harapan


forms
class FormHarapan(ModelForm):
    class Meta:
        model = Harapan
        fields = "__all__"

        widgets = {
            'nama' : forms.TextInput({'class' : 'form-control', 'placeholder':'Pemimpi'}),
            'isi' : forms.Textarea({'class' : 'form-control','maxlength':'100', 'placeholder':'Saya berharap kedepannya...'}),
        }
        

testimoni/forms.py
from django import forms
from django.forms import ModelForm
from django.forms import fields
from testimoni.models import Testimoni


#forms
class FormTestimoni(ModelForm):
    class Meta:
        model = Testimoni
        fields = "__all__"

        widgets = {
            'nama' : forms.TextInput({'class' : 'form-control', 'placeholder':'Mang Oleh'}),
            'isi' : forms.Textarea({'class' : 'form-control','maxlength':'100', 'placeholder':'Donavid menurut saya...'}),
        }
        

about_us/views.py
from django.shortcuts import render

# Create your views here.
def about(request):
    return render(request, 'about.html')

donasi_apd/views.py
from django.shortcuts import render, redirect
from .models import Donasiapd

# Create your views here.
#start
def list_program(request):
    programs = Donasiapd.objects.all()
    response = {'programs': programs}
    return render(request, 'donasi_apd.html', response)


def list_donatur(request, program):
    donasi_total = Donasiapd.objects.get(pk=program)
    nama_program = Donasiapd.objects.get(pk=program).name
    response = {
        'donasi_terkumpul': donasi_total,
        'nama_program' : nama_program,
        }
    return render(request, 'list_donatur_apd.html', response)

homepage/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from homepage.forms import FormHarapan
from homepage.models import Harapan

# Create your views here.
def home(request):
    if request.POST:
        form = FormHarapan(request.POST)
        if form.is_valid:
            form.save()
            form = FormHarapan()
            return HttpResponseRedirect('/')
    else:
        form = FormHarapan()
        harapans = Harapan.objects.all()
        context = {
            'harapans':harapans,
            'form':form
        }
        return render(request, 'home.html', context)

testimoni/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from testimoni.forms import FormTestimoni
from testimoni.models import Testimoni

# Create your views here.
def testimoni(request):
    if request.POST:
        form = FormTestimoni(request.POST)
        if form.is_valid:
            form.save()
            form = FormTestimoni()
            return HttpResponseRedirect('/testimoni/')
    else:
        form = FormTestimoni()
        testimonis = Testimoni.objects.all()
        context = {
            'testimonis':testimonis,
            'form':form
        }
        return render(request, 'testimoni.html', context)
    

Login/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}

{% endblock %}

{% block headone %}
<link rel="stylesheet" type="text/css" href="{% static 'css/homepage.css' %}">
{% endblock %}

{% block content %}

<div id="tk_container">
    <style>
        #tk_container{
            color: rgb(0, 0, 0);
            height: 100vh;
            padding-top: 5rem;
        }

    </style>

<div class="center pt-4 mb-4 pb-4">

        <h1 id="tulisan_line">Login</h1>
</div>

<div class="row center" id="login_attr">
        <div class="col-md-6 col-md-offset-3">
            <div class="rata-tengah">
                <!-- <div class="judul">
                    <p>Login Page</p>
                </div> -->
                <form action="{% url 'login:validate' %}" method="POST" style="margin-bottom: 40px;">
                    {% csrf_token %}
                    <p>
                        <label for="username"> <i class="fa fa-user" aria-hidden="true"></i> Username </label>
                        <input type="text" id="username" name="username" required>
                    </p>
                    <p>
                        <label for="password"> <i class="fa fa-key" aria-hidden="true"></i> Password</label>
                        <input type="password" id="password" name="password" required>
                    </p>
                    <button type="submit" class="submit">Login</button>
                </form>
                {% comment %} <a href="{% url 'user:register' %}" class="submit"> <i aria-hidden="true"></i> Sign Up </a>   {% endcomment %}
            </div>
        </div>
 
    
</div>

{% endblock %}

User/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}

{% endblock %}

{% block headone %}
<link rel="stylesheet" type="text/css" href="{% static 'css/homepage.css' %}">
{% endblock %}

{% block content %}

<div id="bg_hijau">
<div class="container center mt-4 pt-4 mb-4 pb-4">
<h1 style="margin-top: 60px;">you're logged in as <span id="tulisan_line">{{ user }}</span></h1>
</div>


<div class="container center mb-4 pb-4">
        <div id="tulisan_profil ">
                <p><b>Username:</b> &emsp; {{ user }}</p>
                <p><b>First name:</b> &emsp; {{ user.first_name }}</p>
                <p><b>Last name:</b> &emsp; {{ user.last_name }}</p>
                <p><b>Email: </b>&emsp; &emsp; {{ user.email }}</p>
        </div>
</div>
</div>


{% endblock %}
</div>

User/templates/reg_form.html
{% extends 'base.html' %}
{% load static %}

{% block headone %}
<title>{{user.username}}</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/homepage.css' %}">
{% endblock %}

{% block content %}

<div id="tk_container" style="color: black;">
    
    <div class="center pt-4 mb-1 pb-1 "  >
        <h1 style="margin-top: 65px;">Register</h1>
    </div>

    <div class="center">

        <div class="container" style="margin-bottom: 40px;">

            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="submit" type="submit">Submit</button>
            </form>
        </div>

    </div>




</div>

{% endblock %}

about_us/templates/about.html
{% extends "base.html" %}
{% load static %}

{% block headone %}
    <title>About</title>
    <link rel="stylesheet" type="text/css" href="{% static '/css/about.css' %}">
{% endblock %}



{% block content %}
    <div id="gambar-atas">
        <p class="judul">About Us</p>
    </div>

    <div class="container-tulisan">
        <div class="bagian-text">
            <p class="judulAbout">Siapa Kami?</p>
            <p class="penjelasan">Kami adalah lima mahasiswa yang membuat wadah yaitu sebuah organisasi non-profit yang menggalang dana untuk membantu tenaga kesehatan membeli APD dan membeli bahan bantuan sosial.</p>
        </div>
        <div class="bagian-text">
            <p class="judulAbout">Visi</p>
            <p class="penjelasan">Menjadi platform bantuan yang efektif untuk membantu masyarakat yang mengalami kesulitan dalam masa pandemi.</p>
        </div>
        <div class="bagian-text">
            <p class="judulAbout">Misi</p>
            <p class="penjelasan">Membantu mengurangi krisis APD untuk tenaga kesehatan dan memberi bantuan sosial.</p>
        </div>
    </div>
    
    
    <!-- uwu -->
{% endblock %}

donasi_apd/templates/donasi_apd.html
{% extends "base.html" %}
{% load static %}


{% block headone %}
<title>Donasi APD</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/donasi_apd.css' %}">
{% endblock %}


{% block content %}

<div class="container-fluid bg-1">
    <h1 style="color:#000000;" class="judul">Donasi APD</h1>
    <div class="headerapd text-center">
        <img src="{% static 'img/apdcover.jpg' %}">
        <br></br>
        <a href="/donasi-apd/#program-donasi" style="padding-bottom: 50px; " class="center">
            <button type="submit" class="btn rounded-pill" style="background-color: #772E25; color: #ffffff;">Mulai
                Berdonasi!</button>
        </a>

        <h1 style="color:#772E25;" class="judul-deskripsi text-left">Tahukah Anda?</h1>
        <br></br>
        <p class="text-left"> Kurangnya suplai APD membuat banyak dokter memakai ulang masker dan sarung tangan karena stok yang sedikit, dan banyak yang menggunakan jas hujan karena baju APD sangat mahal dan terbatas.</p>
        <br></br>
        <h3 class="text-right">Ayo bantu donasi, agar para pahlawan tidak beresiko terpapar Covid!</h3>
        <br></br>
    </div>
</div>

<div class="container-fluid" id="program_donasi">

    <div id="program-donasi">
        <p class="judulProgramDonasi">Program Donasi</p>

        <div class="row ">
            {% if programs %}
            {% for program in programs %}

            <div class="col-lg-4 col-sm-6 mb-4">
                <div class="card">
                    <img class="card-img-top" src='/{{ program.photo }}'>


                    <div class="card-body">
                        <h5 class="card-title">{{ program.name }}</h5>
                        <p class="card-text">Harga: Rp.{{ program.target }}/buah</p>

                        <div class="center">
                            <a href="{% url 'formulir_donasi_apd' program=program.pk %}" class="btn rounded-pill btn-donasi"
                                style="">Donasi</a>
                            <a href="{% url 'apd:list_donatur_apd' program=program.pk%}"
                                class="btn rounded-pill btn-donasi" style="">Lihat Donatur</a>
                        </div>

                    </div>
                </div>
            </div>

            {% endfor %}

            {% else %}
            <div class="col-sm-12">
                <div class="roundedrec">
                    <div class="insiderec">
                        <h4 class="w3-left-align" style="color: #772E25"><strong>Tidak ada program</strong></h4>
                    </div>
                </div>
            </div>
            {% endif %}

        </div>
        <br>
            <p>More to come..</p>
    </div>
</div>




{% endblock %}

donasi_apd/templates/list_donatur_apd.html
{% extends "base.html" %}
{% load static %}

{% block headone %}
<title>Donasi APD</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/donasi_apd.css' %}">
{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row content">
        <div class="col-sm-12">

            <div></div>
            <h1 class="judulListDonatur center"> Donasi Terkumpul</h1>
            <h6 class="center namaProgramListDonatur">{{ nama_program}}</h6>

            
                <div class="container">
                    {% if donasi_terkumpul.donatur.all.count == 0 %}
                    <h3 class="belum-ada center">Belum ada donasi terkumpul</h3>
                    {% else %}
                    <table class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">Nama Donatur </th>
                                <th scope="col">Donasi Terkumpul</th>
                            </tr>
                        </thead>

                        {% for data in donasi_terkumpul.donatur.all %}
                        {% if data == donasi_terkumpul.donatur.last %}
                        <tr>
                            <td scope="row">{{ data.nama }}</td>
                            <td scope="row">{{ data.jmldonasi }}</td>
                        </tr>
                        {% else %}
                        <tr>
                            <td scope="row">{{ data.nama }}</td>
                            <td scope="row">{{ data.jmldonasi }}</td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                    </table>
                    {% endif %}
                </div>
            <br>

            <div class="center">
                <a href="/donasi-apd/#program-donasi" class="btn rounded-pill btn-donasi center btn-kembali" style="">Kembali</a>
            </div>

        </div>

    </div>
</div>
{% endblock %}