about_us/urls.py
from django.urls import path
from . import views

app_name = 'about_us'

urlpatterns = [
    path('', views.about, name='about'),
]

donasi_apd/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'apd'

urlpatterns = [
    path('', views.list_program, name='list_program'),
    path('<str:program>/', views.list_donatur, name='list_donatur_apd'),
]

donasi_sosial/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'programs'

urlpatterns = [
    path('', views.list_program, name='list_program'),
    path('<str:program>/', views.list_donatur, name='list_donatur'),
]

donavid/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import  static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')), 
    path('login/', include(('Login.urls', 'login'), namespace='login')),
    path('testimoni/', include('testimoni.urls')),
    path('donasi-sosial/', include('donasi_sosial.urls')),
    path('formulir_donasi/', include('formulir_donasi_sosial.urls')),
    path('formulir_donasi_apd/', include('formulir_donasi_apd.urls')),
    path('donasi-apd/', include('donasi_apd.urls')),
    path('about-us/', include('about_us.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

formulir_donasi_apd/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 

urlpatterns = [
    path('<str:program>', views.formulir, name='formulir_donasi_apd'),
    path('donasi_apd_berhasil/', views.berhasil, name='donasi_apd_berhasil'),
]

formulir_donasi_sosial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 

urlpatterns = [
    path('<str:program>', views.formulir, name='formulir_donasi'),
    path('donasi_berhasil/', views.berhasil, name='donasi_berhasil'),
]

homepage/urls.py
from django.contrib import admin
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),


]

testimoni/urls.py
from django.urls import path
from . import views

app_name = 'testimoni'

urlpatterns = [
    path('', views.testimoni, name='testimoni'),
]

Login/models.py
from django.db import models

# Create your models here.

User/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

about_us/models.py
from django.db import models

# Create your models here.

donasi_apd/models.py
from django.db import models
from formulir_donasi_apd.models import DonasiAPD

# Create your models here.
class Donasiapd(models.Model):
    status = models.CharField(max_length=100)
    name   = models.CharField(max_length=200)
    photo  = models.ImageField(upload_to="static/img")
    desc   = models.TextField()
    target = models.IntegerField()
    remDay = models.IntegerField()
    donatur = models.ManyToManyField(DonasiAPD, blank=True)

homepage/models.py
from django.db import models

# Create your models here.
class Harapan(models.Model):
    nama = models.CharField(max_length=15)
    isi = models.TextField(max_length=150)

    def __str__(self):
        return self.nama

testimoni/models.py
from django.db import models

# Create your models here.
class Testimoni(models.Model):
    nama = models.CharField(max_length=15)
    isi = models.TextField(max_length=150)

    def __str__(self):
        return self.nama

User/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import UserProfile

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user

homepage/forms.py
from django import forms
from django.forms import ModelForm
from django.forms import fields
from homepage.models import Harapan


forms
class FormHarapan(ModelForm):
    class Meta:
        model = Harapan
        fields = "__all__"

        widgets = {
            'nama' : forms.TextInput({'class' : 'form-control', 'placeholder':'Pemimpi'}),
            'isi' : forms.Textarea({'class' : 'form-control','maxlength':'100', 'placeholder':'Saya berharap kedepannya...'}),
        }
        

testimoni/forms.py
from django import forms
from django.forms import ModelForm
from django.forms import fields
from testimoni.models import Testimoni


#forms
class FormTestimoni(ModelForm):
    class Meta:
        model = Testimoni
        fields = "__all__"

        widgets = {
            'nama' : forms.TextInput({'class' : 'form-control', 'placeholder':'Mang Oleh'}),
            'isi' : forms.Textarea({'class' : 'form-control','maxlength':'100', 'placeholder':'Donavid menurut saya...'}),
        }
        

about_us/views.py
from django.shortcuts import render

# Create your views here.
def about(request):
    return render(request, 'about.html')

donasi_apd/views.py
from django.shortcuts import render, redirect
from .models import Donasiapd

# Create your views here.
#start
def list_program(request):
    programs = Donasiapd.objects.all()
    response = {'programs': programs}
    return render(request, 'donasi_apd.html', response)


def list_donatur(request, program):
    donasi_total = Donasiapd.objects.get(pk=program)
    nama_program = Donasiapd.objects.get(pk=program).name
    response = {
        'donasi_terkumpul': donasi_total,
        'nama_program' : nama_program,
        }
    return render(request, 'list_donatur_apd.html', response)

donasi_sosial/views.py
from django.shortcuts import render, redirect
from .models import Program

# Create your views here.

def list_program(request):
    programs = Program.objects.all()
    response = {'programs': programs}
    return render(request, 'donasi.html', response)


def list_donatur(request, program):
    donasi_terkumpul = Program.objects.get(pk=program)
    nama_program = Program.objects.get(pk=program).name
    response = {
        'donasi_terkumpul': donasi_terkumpul,
        'nama_program' : nama_program,
        }
    return render(request, 'list_donatur.html', response)

homepage/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from homepage.forms import FormHarapan
from homepage.models import Harapan

# Create your views here.
def home(request):
    if request.POST:
        form = FormHarapan(request.POST)
        if form.is_valid:
            form.save()
            form = FormHarapan()
            return HttpResponseRedirect('/')
    else:
        form = FormHarapan()
        harapans = Harapan.objects.all()
        context = {
            'harapans':harapans,
            'form':form
        }
        return render(request, 'home.html', context)

testimoni/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from testimoni.forms import FormTestimoni
from testimoni.models import Testimoni

# Create your views here.
def testimoni(request):
    if request.POST:
        form = FormTestimoni(request.POST)
        if form.is_valid:
            form.save()
            form = FormTestimoni()
            return HttpResponseRedirect('/testimoni/')
    else:
        form = FormTestimoni()
        testimonis = Testimoni.objects.all()
        context = {
            'testimonis':testimonis,
            'form':form
        }
        return render(request, 'testimoni.html', context)
    

homepage/templates/base-template.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	<!-- <link rel="stylesheet" href="{% static  'base.css' %}"> -->
	<!-- Google Font -->
	<link
		href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;1,200;1,300;1,400;1,500;1,600;1,700&family=Poppins:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;1,200;1,300;1,400&display=swap"
		rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <script
    src="https://code.jquery.com/jquery-3.4.1.js"
    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous"></script>
    <!-- <link rel="stylesheet" href="{% static 'style.css' %}" /> -->
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    {% block headone %}{% endblock %}
	<!-- <link rel="stylesheet" href="https://m.w3newbie.com/you-tube.css"> -->
</head>
<body>
    
    <!-- NAVBAR -->
	<nav class="navbar fixed-top navbar-expand-lg navbar-dark  " style="background-color: #772E25 !important;">

		<a class="navbar-brand" href="/"><img src="{% static 'img/logo.png' %}" style="width:100px;"></a>

		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
			aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav active">

				<li class="nav-item ">
					<a class="nav-link" href="/donasi-apd">Donasi APD</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'programs:list_program' %}">Donasi Sosial</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/testimoni">Testimoni</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/about-us/">About Us</a>
				</li>
				<!-- <li class="nav-item">
					<a class="nav-link" href="">Profil</a>
                </li> -->
                
                {% if user.is_authenticated %}

                    <li class="nav-item mr-4">
                        <a class="nav-link" href="{% url 'user:view_profile' %}">My Profile</a>
                    </li>

                    <li class="nav-item mr-4">
                        <a class="nav-link btn btn-outline-dark" href="{% url 'user:logout' %}">Logout</a>
                    </li>

                    {% else %}

                    <li class="nav-item mr-4">
                        <a class="nav-link btn btn-outline-dark" href="{% url 'Login:login' %}">Login</a>
                    </li>

                    <li class="nav-item mr-4">
                        <a class="nav-link btn btn-outline-dark" href="{% url 'user:register' %}">Register</a>
                    </li>

                    {% endif %}

			</ul>

		</div>

	</nav>


	{% block content %}

	{% endblock %}

	<!-- FOOTER -->
	<footer class="page-footer font-small unique-color-dark" style="background-color: #197278;">
		<div style="background-color: #772E25 !important;">
			<div class="container">
				<!-- Grid row-->
				<div class="row py-4 d-flex align-items-center"></div>
				<!-- Grid row-->
			</div>
		</div>

		<!-- Footer Links -->
		<div class="container text-center text-md-left mt-5">
			<!-- Grid row -->
			<div class="row mt-3">
				<!-- Grid column -->
				<div class="col-md-3 col-lg-2 col-xl-3 mx-auto mb-4" style="align-items: center; justify-content: center; margin-top: 50px;">
					<!-- Content -->
					<img src="{% static 'img/logo.png' %}" style="width:85%;">
				</div>
				<!-- Grid column -->

				<!-- Grid column -->
				<div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

					<!-- Links -->
					<h6 class="text-uppercase font-weight-bold" style="color: white;">ABOUT US</h6>
					<hr class=" mb-4 mt-0 d-inline-block mx-auto">
					<p style="color: white; font-size: 14px;">Donavid adalah organisasi non-profit yang menggalang dana untuk membantu tenaga kesehatan membeli APD dan membeli bahan bantuan sosial.</p>
				</div>

				<!-- Grid column -->
				<div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
					<!-- Links -->
					<h6 class="text-uppercase font-weight-bold" style="color: white;">DEVELOPER</h6>
					<hr class=" mb-4 mt-0 d-inline-block mx-auto">
					<p style="color: white; font-size: 14px;">- Andreas Ilham <br>- Amanda Carrisa <br>- Fadiya Latifah <br>- Faris Muzhaffar <br>- Bima Adinsa</p>
				</div>

				<!-- Grid column -->
				<div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
					<!-- Links -->
					<h6 class="text-uppercase font-weight-bold" style="color: white;">CONTACT US</h6>
					<hr class=" mb-4 mt-0 d-inline-block mx-auto">
					<p style="color: white; font-size: 14px;">donavid@donavid.com</p>
				</div>

				

			</div>
			<!-- Grid row -->

		</div>
		<!-- Footer Links -->

		<!-- Copyright -->
		<div class="footer-copyright text-center py-3" style="background-color: #283C3B;">
			<p style="color: white;">© 2020 Copyright: Kelompok 18 PPW-E</p>
		</div>
		<!-- Copyright -->

	</footer>
	<!-- Footer -->

</body>

</html>

homepage/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	<!-- <link rel="stylesheet" href="{% static  'base.css' %}"> -->
	<!-- Google Font -->
	<link
		href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;1,200;1,300;1,400;1,500;1,600;1,700&family=Poppins:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;1,200;1,300;1,400&display=swap"
		rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <script
    src="https://code.jquery.com/jquery-3.4.1.js"
    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous"></script>
    <!-- <link rel="stylesheet" href="{% static 'style.css' %}" /> -->
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    {% block headone %}{% endblock %}
	<!-- <link rel="stylesheet" href="https://m.w3newbie.com/you-tube.css"> -->
</head>
<body>
    
    <!-- NAVBAR -->
	<nav class="navbar fixed-top navbar-expand-lg navbar-dark  " style="background-color: #772E25 !important;">

		<a class="navbar-brand" href="/"><img src="{% static 'img/logo.png' %}" style="width:100px;"></a>

		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
			aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarNav">
			<ul class="navbar-nav active">

				<li class="nav-item ">
					<a class="nav-link" href="/donasi-apd">Donasi APD</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'programs:list_program' %}">Donasi Sosial</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/testimoni">Testimoni</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="/about-us/">About Us</a>
				</li>
				<!-- <li class="nav-item">
					<a class="nav-link" href="">Profil</a>
                </li> -->
                
                {% if user.is_authenticated %}

                    <li class="nav-item mr-4">
                        <a class="nav-link" href="{% url 'user:view_profile' %}">My Profile</a>
                    </li>

                    <li class="nav-item mr-4">
                        <a class="nav-link btn btn-outline-dark" href="{% url 'user:logout' %}">Logout</a>
                    </li>

                    {% else %}

                    <li class="nav-item mr-4">
                        <a class="nav-link btn btn-outline-dark" href="{% url 'Login:login' %}">Login</a>
                    </li>

                    <li class="nav-item mr-4">
                        <a class="nav-link btn btn-outline-dark" href="{% url 'user:register' %}">Register</a>
                    </li>

                    {% endif %}

			</ul>

		</div>

	</nav>


	{% block content %}

	{% endblock %}

	<!-- FOOTER -->
	<footer class="page-footer font-small unique-color-dark" style="background-color: #197278;">
		<div style="background-color: #772E25 !important;">
			<div class="container">
				<!-- Grid row-->
				<div class="row py-4 d-flex align-items-center"></div>
				<!-- Grid row-->
			</div>
		</div>

		<!-- Footer Links -->
		<div class="container text-center text-md-left mt-5">
			<!-- Grid row -->
			<div class="row mt-3">
				<!-- Grid column -->
				<div class="col-md-3 col-lg-2 col-xl-3 mx-auto mb-4" style="align-items: center; justify-content: center; margin-top: 50px;">
					<!-- Content -->
					<img src="{% static 'img/logo.png' %}" style="width:85%;">
				</div>
				<!-- Grid column -->

				<!-- Grid column -->
				<div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

					<!-- Links -->
					<h6 class="text-uppercase font-weight-bold" style="color: white;">ABOUT US</h6>
					<hr class=" mb-4 mt-0 d-inline-block mx-auto">
					<p style="color: white; font-size: 14px;">Donavid adalah organisasi non-profit yang menggalang dana untuk membantu tenaga kesehatan membeli APD dan membeli bahan bantuan sosial.</p>
				</div>

				<!-- Grid column -->
				<div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
					<!-- Links -->
					<h6 class="text-uppercase font-weight-bold" style="color: white;">DEVELOPER</h6>
					<hr class=" mb-4 mt-0 d-inline-block mx-auto">
					<p style="color: white; font-size: 14px;">- Andreas Ilham <br>- Amanda Carrisa <br>- Fadiya Latifah <br>- Faris Muzhaffar <br>- Bima Adinsa</p>
				</div>

				<!-- Grid column -->
				<div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
					<!-- Links -->
					<h6 class="text-uppercase font-weight-bold" style="color: white;">CONTACT US</h6>
					<hr class=" mb-4 mt-0 d-inline-block mx-auto">
					<p style="color: white; font-size: 14px;">donavid@donavid.com</p>
				</div>

				

			</div>
			<!-- Grid row -->

		</div>
		<!-- Footer Links -->

		<!-- Copyright -->
		<div class="footer-copyright text-center py-3" style="background-color: #283C3B;">
			<p style="color: white;">© 2020 Copyright: Kelompok 18 PPW-E</p>
		</div>
		<!-- Copyright -->

	</footer>
	<!-- Footer -->

</body>

</html>

homepage/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block headone %}
<title>Donavid</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/homepage.css' %}">
{% endblock %}

{% block content %}
    <div class="atas"> 
        <div class="container padding-atas">
            <img class="logo_home" src="../static/img/logo.png" alt="">
            <p class="teks" style="color: white;">Pandemi COVID-19 telah membuat ratusan ribu bahkan jurtaan orang mengalami kerugian ekonomi. Dengan Donavid, masyarakat bisa menggalang dana untuk beragam hal yang dapat meringankan beban dari pandemi COVID-19 ini</p>
            
            <a href="/donasi-apd/" style="padding-bottom: 50px; " >
                <button type="submit" class="btn rounded-pill" style="background-color: #772E25; color: #ffffff;">Donasi APD</button>
            </a>
            <a href="/donasi-sosial/" style="padding-bottom: 50px; " >
                <button type="submit" class="btn rounded-pill" style="background-color: #772E25; color: #ffffff;">Donasi Sosial</button>
            </a>

            
        </div>
    </div>

    <div class="tengah">
        <h1 class="teks_judul">Ayo Menjadi Bagian Dari Donavid!</h1>
    </div>

    <div class="row content">
        <!-- FORMULIR DONASI -->
        <div class="col-md-6 order-2 order-md-1">
            <p class="teks2">Donavid adalah organisasi non-profit yang menggalang dana untuk membantu tenaga kesehatan membeli APD dan membeli bahan bantuan sosial.</p>
        </div>
        <!-- FOTO DONASI -->
        <div class="col-md-6 center order-1 order-md-2">
            <img class="fotoDetailDonasi" src='../static/img/gambar_tengah_home.png'>
        </div>
    </div>

    <div style="height: 50px;"></div>

    <div class="bawah">
        <h1 class="teks_judul">Ayo Berikan Harapanmu dalam Menghadapi Situasi Ini</h1>
    </div>

    <div class="untuk_form">
        <div class="bagian-text">
            <div class="row">
                {% for harapan in harapans %}
                <div class="col-md-4 mb-4">
                    <div class="card" style="height: 300px; margin-top: 20px; margin-left: 35px;">
                        <div class="card-body">
                            <div class="harapan-textfield"> 
                                <p style="padding-top: 30px;">{{ harapan.isi }}</p>
                            </div>
                            <div class="harapan-nama">
                                <p style="right: 120px; position: absolute;">-{{ harapan.nama }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="bagian-text">
            <form action="/" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="kananin">
                    <button class="btn rounded-pill btn-donasi">Kirim</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

homepage/templates/homepage.html
{% extends 'base-template.html' %}
{% load static %}
{% block title %}
Donatsi
{% endblock %}

{% block scripts %}
<script src="{% static 'scripts/getDataSemuaPermohonan.js' %}"></script>
{% endblock %}

{% block content %}

<div style="height: 1000px;">halo</div>
<a href="/">APAAAAAAAAAAA</a>

{% endblock %}
</div>

testimoni/templates/testimoni.html
{% extends "base.html" %}
{% load static %}


    {% block headone %}
    <title>Testimoni</title>
    <link rel="stylesheet" href="{% static '/css/testimoni.css' %}">
    {% endblock %}




{% block content %}
    <div class="container-tulisan">
        <div class="bagian-text">
            <p class="judul-testimoni">Testimoni</p>
            <div class="row">
                {% for testimoni in testimonis %}
                <div class="col-md-4 mb-4">
                        <div class="card" style="height: 360px;">
                            <div class="card-body">
                                <div class="testimoni-textfield">
                                    <p style="padding-top: 40px;">{{ testimoni.isi }}</p>
                                </div>
                                <div class="testimoni-nama">
                                    <p style="right: 0; position: absolute;">- {{ testimoni.nama }}</p>
                                </div>
                            </div>
                        </div>
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="bagian-text">
            <p class="judul-testimoni">Berikan Testimoni</p>
            <form action="/testimoni/" method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="kananin">
                    <button class="btn rounded-pill btn-donasi">Kirim</button>
                </div>
            </form>
        </div>
    </div>
    
    
    <!-- uwu -->
{% endblock %}


    